"""
app/pipeline/stage2_classifier.py

Local classifier stage. Runs after Stage 1 (keyword/PII/profanity) and before
Stage 3 (FAISS) and the LLM. Uses a LogisticRegression trained on MiniLM embeddings.

Decision logic:
  confidence >= CONFIDENT_THRESHOLD (0.80) and category != NONE → BLOCK immediately
  confidence >= ESCALATE_THRESHOLD  (0.50)                      → pass hint to FAISS/LLM
  confidence <  ESCALATE_THRESHOLD                              → ALLOW (classifier is
                                                                   confident it's clean)

The embedding model is the same one used by FAISS — loaded once at startup, shared.
"""

import pickle
import numpy as np
from dataclasses import dataclass
from pathlib import Path

CLASSIFIER_PATH = Path("data/classifier.pkl")


@dataclass
class ClassifierResult:
    decision: str          # "BLOCK", "HINT", "ALLOW"
    category: str          # e.g. "THREAT", "SCAM", "NONE"
    confidence: float      # 0.0 – 1.0
    hint: str | None = None


class Stage2Classifier:
    """
    Lightweight local classifier. Loads once, predicts in ~2ms.
    Requires: data/classifier.pkl (generated by scripts/train_classifier.py)
    """
    _loaded: bool = False
    _clf = None
    _le = None
    _model = None
    _confident_threshold: float = 0.80
    _escalate_threshold: float = 0.50

    @classmethod
    def load(cls) -> bool:
        """
        Loads classifier from disk. Returns True if successful, False if
        classifier file not found (pipeline continues without it gracefully).
        """
        if cls._loaded:
            return True

        if not CLASSIFIER_PATH.exists():
            return False

        try:
            with open(CLASSIFIER_PATH, "rb") as f:
                data = pickle.load(f)

            cls._clf = data["clf"]
            cls._le = data["le"]
            cls._confident_threshold = data.get("confident_threshold", 0.80)
            cls._escalate_threshold = data.get("escalate_threshold", 0.50)
            model_name = data.get("embedding_model", "paraphrase-multilingual-MiniLM-L12-v2")

            # Import here to avoid circular imports at module load
            from sentence_transformers import SentenceTransformer
            cls._model = SentenceTransformer(model_name)
            cls._loaded = True
            return True

        except Exception as e:
            # Log but don't crash — pipeline works without classifier
            print(f"[Stage2Classifier] Failed to load classifier: {e}")
            return False

    @classmethod
    def is_available(cls) -> bool:
        return cls._loaded or cls.load()

    @classmethod
    def predict(cls, text: str) -> ClassifierResult:
        """
        Predicts category and confidence for a given text.
        Returns ClassifierResult with decision, category, and confidence.
        """
        if not cls.is_available():
            # Classifier not trained yet — pass through to FAISS/LLM
            return ClassifierResult(
                decision="ALLOW",
                category="NONE",
                confidence=0.0,
                hint="classifier_unavailable"
            )

        try:
            embedding = cls._model.encode([text], show_progress_bar=False)
            proba = cls._clf.predict_proba(embedding)[0]
            confidence = float(proba.max())
            label_idx = int(proba.argmax())
            category = cls._le.inverse_transform([label_idx])[0]

            # Decision logic based on confidence thresholds
            if category == "NONE":
                if confidence >= cls._confident_threshold:
                    # Very confident it's clean — ALLOW without further checks
                    return ClassifierResult(
                        decision="ALLOW",
                        category="NONE",
                        confidence=confidence
                    )
                else:
                    # Uncertain — pass to FAISS/LLM
                    return ClassifierResult(
                        decision="HINT",
                        category="NONE",
                        confidence=confidence,
                        hint=f"Classifier uncertain (conf:{confidence:.2f})"
                    )

            elif confidence >= cls._confident_threshold:
                # Confident violation — BLOCK immediately, no LLM needed
                return ClassifierResult(
                    decision="BLOCK",
                    category=category,
                    confidence=confidence
                )

            elif confidence >= cls._escalate_threshold:
                # Possible violation — send as hint to LLM
                return ClassifierResult(
                    decision="HINT",
                    category=category,
                    confidence=confidence,
                    hint=f"Classifier suspects {category} ({confidence:.0%} confidence)"
                )

            else:
                # Low confidence — treat as clean, let FAISS/LLM decide
                return ClassifierResult(
                    decision="ALLOW",
                    category="NONE",
                    confidence=confidence
                )

        except Exception as e:
            print(f"[Stage2Classifier] Prediction error: {e}")
            return ClassifierResult(
                decision="ALLOW",
                category="NONE",
                confidence=0.0,
                hint="classifier_error"
            )