"""Initial tables

Revision ID: 9d387b460929
Revises: 
Create Date: 2026-03-09 10:29:18.503754+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d387b460929'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('profile_id_whitelist', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('feedback_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('template_text', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_templates_id'), 'feedback_templates', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_templates_language_code'), 'feedback_templates', ['language_code'], unique=False)
    op.create_index(op.f('ix_feedback_templates_rule_type'), 'feedback_templates', ['rule_type'], unique=False)
    op.create_table('llm_provider_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_provider_logs_id'), 'llm_provider_logs', ['id'], unique=False)
    op.create_table('rules_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('group_topic', sa.String(), nullable=False),
    sa.Column('global_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('group_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('keywords_by_language', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spam_limit', sa.Integer(), nullable=True),
    sa.Column('spam_window_s', sa.Integer(), nullable=True),
    sa.Column('faiss_threshold', sa.Float(), nullable=True),
    sa.Column('llm_confidence_threshold_en', sa.Float(), nullable=True),
    sa.Column('llm_confidence_threshold_indic', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_profiles_id'), 'rules_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_rules_profiles_profile_id'), 'rules_profiles', ['profile_id'], unique=True)
    op.create_table('banned_topic_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('topic_label', sa.String(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rules_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banned_topic_embeddings_id'), 'banned_topic_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_banned_topic_embeddings_profile_id'), 'banned_topic_embeddings', ['profile_id'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('message_hash', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('stage_triggered', sa.String(), nullable=True),
    sa.Column('violated_rule', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_stage0_ms', sa.Integer(), nullable=True),
    sa.Column('latency_stage1_ms', sa.Integer(), nullable=True),
    sa.Column('latency_stage2_ms', sa.Integer(), nullable=True),
    sa.Column('latency_stage3_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_api_key_id'), 'moderation_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_id'), 'moderation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_message_hash'), 'moderation_logs', ['message_hash'], unique=False)
    op.create_index(op.f('ix_moderation_logs_profile_id'), 'moderation_logs', ['profile_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('template_text', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['rules_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_profile_id'), 'prompt_templates', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_profile_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_moderation_logs_profile_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_message_hash'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_api_key_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_banned_topic_embeddings_profile_id'), table_name='banned_topic_embeddings')
    op.drop_index(op.f('ix_banned_topic_embeddings_id'), table_name='banned_topic_embeddings')
    op.drop_table('banned_topic_embeddings')
    op.drop_index(op.f('ix_rules_profiles_profile_id'), table_name='rules_profiles')
    op.drop_index(op.f('ix_rules_profiles_id'), table_name='rules_profiles')
    op.drop_table('rules_profiles')
    op.drop_index(op.f('ix_llm_provider_logs_id'), table_name='llm_provider_logs')
    op.drop_table('llm_provider_logs')
    op.drop_index(op.f('ix_feedback_templates_rule_type'), table_name='feedback_templates')
    op.drop_index(op.f('ix_feedback_templates_language_code'), table_name='feedback_templates')
    op.drop_index(op.f('ix_feedback_templates_id'), table_name='feedback_templates')
    op.drop_table('feedback_templates')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
